### ISSUE TITLE
Lavish Mishra

### ISSUE THREAD

**Issue by aflies1** [promazo/Sourcing#108]
Would not be able to start on May 23rd. (would be available for onboarding
- Would need offer letters for summer and then the fall
- Can work during the fall and beyond (only taking 6 credit hours)
- Very strong background in AWS
- Couldn't get a read on how much dev work he has done, but he mentioned he is very experienced in Java
- Seems personable and hungry for an opportunity

**Comment by albertoleon7794** [comment]
Interview questions: https://docs.google.com/document/d/1MTRyX_96l2iLoxErXV1H-kzN5LnE-0s1DXnsY0sPgb0/edit?usp=sharing

**Comment by albertoleon7794** [comment]
Score: https://docs.google.com/spreadsheets/d/11WCytb3tYyet0f4IJ0npFTnldDtFrxL0Mx9M8MzaZ0Y/edit?usp=sharing

**Comment by albertoleon7794** [comment]
Notes:

- Average candidate in the graduate category.
- Average score in comparison to other graduate candidates.
- Average behavioral skills.
In general I think that this is a very good candidate. But I think we have better candidates in the pipeline.

**Comment by ldaudet** [comment]
Lavish Mishra

    Do they have a strong understanding of Java, can they pick things up quickly

He started to code in C/C++ in high school. He did his undergraduate in CS, and got into Java. He learned about the process of coding, and the techniques behind it. He worked in multiple projects since then, including ML.

He then working for Cognizant for 3 years. He then felt like he wanted to deepened his skills, and went for the MS at Buffalo. He's best at Java, then Python then C++. 

He also have some fairly broad knowledge in CS, having a good background in cloud, both AWS and GCP and having even dable in app dev for a hackaton.

    Can they learn quickly on the fly? Schwab isn't going to expect them to know everything but the faster they pick things up the better. This team will start slow with some QA and get up to speed on their overall project and codebase before we start to take on dev tasks. (they will be working and integrated into their AGILE/SCRUM)

He's more of an autodidact, so that would let me hope that he would be able to get up to speed on things.

When working on a problem that he never saw before, he would first go to the more experienced devs, and then start researching the issue by himself. When working on a problem he would work on it incrementaly, hoping in the code, getting a kernel running, and then adding the specs to it little by littel.

    Great communication - if they don't know something we'd want them to try and figure it out on their own, but ask our manager and senior devs for help. This is a 12 month project so it will be important for them to build strong communication/relationships with the team and Schwab's devs.

He used SCRUM while at cognizant. He likes a more structured work environment, though he can also appreciate a bit of a flexibility wihthin the framework.
